# Generated by Django 2.1.1 on 2018-10-20 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Magic',
            new_name='MapType',
        ),
        migrations.DeleteModel(
            name='OracleRecord',
        ),
        migrations.RenameField(
            model_name='maptype',
            old_name='name',
            new_name='maptype',
        ),
    ]
