# Generated by Django 2.1.1 on 2018-10-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_auto_20181020_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_genders', models.CharField(max_length=100)),
                ('male', models.CharField(max_length=100)),
                ('female', models.CharField(max_length=100)),
            ],
        ),
    ]
