# Generated by Django 2.1.1 on 2018-10-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_hs', models.CharField(max_length=100)),
                ('hs', models.CharField(max_length=100)),
                ('some_college', models.CharField(max_length=100)),
                ('college_plus', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('below_poverty', models.CharField(max_length=100)),
                ('above_poverty', models.CharField(max_length=100)),
            ],
        ),
    ]
