# Generated by Django 2.1.1 on 2018-10-30 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0006_auto_20181030_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IncomeLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='education',
            name='education_level',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='MapType',
        ),
        migrations.RenameField(
            model_name='educationlevel',
            old_name='education_level',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='gender',
            old_name='genders',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.AddField(
            model_name='incomedata',
            name='education_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.EducationLevel'),
        ),
        migrations.AddField(
            model_name='incomedata',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.Gender'),
        ),
        migrations.AddField(
            model_name='incomedata',
            name='income_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.IncomeLevel'),
        ),
    ]
