# Generated by Django 2.1.2 on 2018-11-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0008_auto_20181030_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='fips',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='abbr',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
